baseURL = "https://octant.dev"
languageCode = "en-us"
title = "Octant"

contentDir = "content"

enableGitInfo = true

[params]
  description = "Validate your Kubernetes configuration"
  slack = "https://kubernetes.slack.com/app_redirect?channel=CM37M9FCG"
  github = "https://github.com/vmware-tanzu/octant"
  twitter = "https://twitter.com/projectoctant"
  rss = "/feed.xml"

[permalinks]
  posts = "/:filename"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.nav]]
    name = "Community"
    url = "/community/"
    weight = 3
  [[menu.nav]]
    name = "Documentation"
    url = "/docs/"
    weight = 4
  [[menu.nav]]
    name = "Resources"
    url = "/resources/"
    weight = 5